name: lunar
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex==0.1=main
  - _openmp_mutex==5.1=1_gnu
  - blas==1.0=mkl
  - bzip2==1.0.8=h5eee18b_5
  - ca-certificates==2023.12.12=h06a4308_0
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - filelock==3.13.1=py310h06a4308_0
  - gmp==6.2.1=h295c915_3
  - gmpy2==2.1.2=py310heeb90bb_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - jinja2==3.1.3=py310h06a4308_0
  - ld_impl_linux-64==2.38=h1181459_1
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcusolver
  - libcusparse
  - libffi==3.4.4=h6a678d5_0
  - libgcc-ng==11.2.0=h1234567_1
  - libgfortran-ng==7.5.0=ha8ba4b0_17
  - libgfortran4==7.5.0=ha8ba4b0_17
  - libgomp==11.2.0=h1234567_1
  - libnpp=12.0.2.50
  - libnvjpeg=12.1.0.39
  - libstdcxx-ng==11.2.0=h1234567_1
  - libuuid==1.41.5=h5eee18b_0
  - llvm-openmp==14.0.6=h9e868ea_0
  - markupsafe==2.1.3=py310h5eee18b_0
  - mkl==2023.1.0=h213fc3f_46344
  - mpc==1.1.0=h10f8cd9_1
  - mpfr==4.0.2=hb69a4c5_1
  - mpi4py==3.1.4=py310hfc96bbd_0
  - mpi==1.0=mpich
  - mpich==3.3.2=hc856adb_0
  - mpmath==1.3.0=py310h06a4308_0
  - ncurses==6.4=h6a678d5_0
  - networkx==3.1=py310h06a4308_0
  - openssl==3.0.13=h7f8727e_0
  - pip==23.3.1=py310h06a4308_0
  - python==3.10.13=h955ad1f_0
  - pytorch-cuda==12.1=ha16c6d3_6
  - pytorch-mutex==1.0=cuda
  - pytorch==2.2.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pyyaml==6.0.1=py310h5eee18b_0
  - readline==8.2=h5eee18b_0
  - setuptools==68.2.2=py310h06a4308_0
  - sqlite==3.41.2=h5eee18b_0
  - sympy==1.12=py310h06a4308_0
  - tbb==2021.8.0=hdb19cb5_0
  - tk==8.6.12=h1ccaba5_0
  - torchtriton==2.2.0=py310
  - typing_extensions==4.9.0=py310h06a4308_1
  - wheel==0.41.2=py310h06a4308_0
  - xz==5.4.6=h5eee18b_0
  - yaml==0.2.5=h7b6447c_0
  - zlib==1.2.13=h5eee18b_0
